version: '2'

services:
    go:
      container_name: gowebapp
      image: goweb
      build:
        context: .
        dockerfile: .docker/go.dockerfile
      env_file:
        - .docker/env/web.env
      ports:
        - "5000:5000"
      networks:
        - db-network

    postgres:
      container_name: postgres
      image: my-postgres
      volumes:
        - ./data:/var/lib/postgresql/data
      build:
          context: .
          dockerfile: .docker/postgres.dockerfile
      networks:
        - db-network

networks:
  db-network:
    driver: bridge
