version: '2'

services:
    go:
      container_name: gowebapp
      image: goweb
      build:
        context: .
        dockerfile: .docker/go.dockerfile
      ports:
        - "80:5000"
      networks:
        - db-network

    postgres:
      container_name: postgres
      image: my-postgres
      build:
          context: .
          dockerfile: .docker/postgres.dockerfile
      networks:
        - db-network

networks:
  db-network:
    driver: bridge
